# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import largeimage_pb2 as largeimage__pb2


class TransferRPCStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Transfer = channel.stream_unary(
        '/LargeImageProc.TransferRPC/Transfer',
        request_serializer=largeimage__pb2.OneImage.SerializeToString,
        response_deserializer=largeimage__pb2.Status.FromString,
        )


class TransferRPCServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Transfer(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TransferRPCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Transfer': grpc.stream_unary_rpc_method_handler(
          servicer.Transfer,
          request_deserializer=largeimage__pb2.OneImage.FromString,
          response_serializer=largeimage__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'LargeImageProc.TransferRPC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
